(define (make-tile type image) (cons type image))
(define tile-type car)
(define tile-image cdr)

(define air (empty-scene 0 0))
(define wall-tile-1 (bitmap "images/tiles/wall-tile-1.png"))
(define wall-tile-2 (bitmap "images/tiles/wall-tile-2.png"))
(define ground-tile-1 (bitmap "images/tiles/ground-tile-1.png"))
(define ground-tile-2 (bitmap "images/tiles/ground-tile-2.png"))
(define ground-tile-3 (bitmap "images/tiles/ground-tile-3.png"))
(define ground-tile-4 (bitmap "images/tiles/ground-tile-4.png"))
(define ground-wall-corner-tile-1 (bitmap "images/tiles/ground-wall-corner-tile-1.png"))
(define ground-wall-corner-tile-2 (bitmap "images/tiles/ground-wall-corner-tile-2.png"))
(define block-tile-1 (bitmap "images/tiles/block-tile-1.png"))
(define grass-1 (bitmap "images/tiles/grass-1.png"))
(define mushroom-1 (bitmap "images/tiles/mushroom-1.png"))

(define test1 (rectangle 64 64 "solid" "black"))
(define t1 (make-tile 1 test1))
(define test2 (rectangle 64 64 "solid" "blue"))

(define ai (make-tile 0 (empty-scene 0 0)))
(define w1 (make-tile 1 wall-tile-1))
(define w2 (make-tile 1 wall-tile-2))
(define w3 (make-tile 1 ground-wall-corner-tile-1))
(define w4 (make-tile 1 ground-wall-corner-tile-2))
(define g1 (make-tile 1 ground-tile-1))
(define g2 (make-tile 1 ground-tile-2))
(define g3 (make-tile 1 ground-tile-3))
(define g4 (make-tile 1 ground-tile-4))
(define b1 (make-tile 1 block-tile-1))
(define d1 (make-tile 0 grass-1))
(define d2 (make-tile 0 mushroom-1))

(define ck (make-tile 2 (empty-scene 0 0)))


